# **DECONVOLUTION**

In [17]:
from __future__ import print_function
import os
import cv2
import histomicstk as htk

import numpy as np
import scipy as sp

import skimage.io
import skimage.measure
import skimage.color

import time
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
%matplotlib inline

#Some nice default configuration for plots
plt.rcParams['figure.figsize'] = 15, 15
plt.rcParams['image.cmap'] = 'gray'
titlesize = 24

import copy
from tqdm import tqdm

In [18]:
base_img_path = 'val/'
images = os.listdir(base_img_path)


***Approach-1*** - Supervised color deconvolution with a known stain matrix

In [19]:
def normalize(stain_OD):
    normal_OD = []
    for stain in stain_OD:
        print(stain)
        deno = 0
        pow = [e*e for e in stain]
        total = sum(pow)
        temp = []
        for ele in stain:
            temp.append(ele/math.sqrt(total))
        normal_OD.append(temp)
    return np.asarray(normal_OD)

In [20]:

def convert_to_optical_densities(rgb,r0,g0,b0):
    OD = rgb.astype(float)
    OD[:,:,0] /= r0
    OD[:,:,1] /= g0
    OD[:,:,2] /= b0

    return -np.log(OD)

def color_deconvolution(rgb,r0,g0,b0,verbose=False):
    stain_OD = np.asarray([[0.18,0.20,0.08],[0.01,0.13,0.0166],[0.10,0.21,0.29]]) #hematoxylin, eosyn, DAB

    """
    n = []
    for r in stain_OD:
        n.append(r/norm(r))
    normalized_OD = np.asarray(n)
    """
    
    normalized_OD = normalize(stain_OD)
    
    #D = inv(normalized_OD)
    D = np.linalg.inv(normalized_OD)
    
    OD = convert_to_optical_densities(rgb,r0,g0,b0)

    ODmax = np.max(OD,axis=2)
    plt.figure()
    plt.imshow(ODmax>.1)

    # reshape image on row per pixel
    rOD = np.reshape(OD,(-1,3))
    # do the deconvolution
    rC = np.dot(rOD,D)

    #restore image shape
    C = np.reshape(rC,OD.shape)

    #remove problematic pixels from the the mask
    ODmax[np.isnan(C[:,:,0])] = 0
    ODmax[np.isnan(C[:,:,1])] = 0
    ODmax[np.isnan(C[:,:,2])] = 0
    ODmax[np.isinf(C[:,:,0])] = 0
    ODmax[np.isinf(C[:,:,1])] = 0
    ODmax[np.isinf(C[:,:,2])] = 0

    return (ODmax,C)

In [21]:
def supervised_deconvolve(imInput):
    # create stain to color map
    stain_color_map = htk.preprocessing.color_deconvolution.stain_color_map
    print('stain_color_map:', stain_color_map, sep='\n')

    # specify stains of input image
    stains = ['hematoxylin',  # nuclei stain
            'eosin',        # cytoplasm stain
            'null']         # set to null if input contains only two stains

    # create stain matrix
    W = np.array([stain_color_map[st] for st in stains]).T

    # perform standard color deconvolution
    imDeconvolved = htk.preprocessing.color_deconvolution.color_deconvolution(imInput, W)
    return imDeconvolved

In [22]:
supervised_time = []
images.sort()
for i in range(0,len(images)):
    inputImageFile = 'val/'+ images[i]
    imInput = skimage.io.imread(inputImageFile)[:, :, :3]
    t1= time.time()
    imDeconvolved =  supervised_deconvolve(imInput)
    supervised_time.append(time.time()-t1)
    im_c = cv2.hconcat([imDeconvolved.Stains[:, :, 0], imDeconvolved.Stains[:, :, 1]])
    cv2.imwrite("temp.jpg",im_c)
    im_dec = cv2.imread("temp.jpg")
    im_c = cv2.hconcat([imInput, im_dec])
    if i==0:
        final = copy.deepcopy(im_c)
    else:
        final = cv2.vconcat([final, im_c])
#cv2.imwrite("supervised.jpg", final)


stain_color_map:
{'hematoxylin': [0.65, 0.7, 0.29], 'eosin': [0.07, 0.99, 0.11], 'dab': [0.27, 0.57, 0.78], 'null': [0.0, 0.0, 0.0]}
stain_color_map:
{'hematoxylin': [0.65, 0.7, 0.29], 'eosin': [0.07, 0.99, 0.11], 'dab': [0.27, 0.57, 0.78], 'null': [0.0, 0.0, 0.0]}
stain_color_map:
{'hematoxylin': [0.65, 0.7, 0.29], 'eosin': [0.07, 0.99, 0.11], 'dab': [0.27, 0.57, 0.78], 'null': [0.0, 0.0, 0.0]}
stain_color_map:
{'hematoxylin': [0.65, 0.7, 0.29], 'eosin': [0.07, 0.99, 0.11], 'dab': [0.27, 0.57, 0.78], 'null': [0.0, 0.0, 0.0]}
stain_color_map:
{'hematoxylin': [0.65, 0.7, 0.29], 'eosin': [0.07, 0.99, 0.11], 'dab': [0.27, 0.57, 0.78], 'null': [0.0, 0.0, 0.0]}
stain_color_map:
{'hematoxylin': [0.65, 0.7, 0.29], 'eosin': [0.07, 0.99, 0.11], 'dab': [0.27, 0.57, 0.78], 'null': [0.0, 0.0, 0.0]}
stain_color_map:
{'hematoxylin': [0.65, 0.7, 0.29], 'eosin': [0.07, 0.99, 0.11], 'dab': [0.27, 0.57, 0.78], 'null': [0.0, 0.0, 0.0]}
stain_color_map:
{'hematoxylin': [0.65, 0.7, 0.29], 'eosin': [0.07, 0

In [23]:
sum(supervised_time)/len(images)

0.03678997357686361

***Approach-2***

In [ ]:

inputImageFile = 'val/'+ images[0]
imInput = skimage.io.imread(inputImageFile)[:, :, :3]

In [ ]:
imInput.shape

In [ ]:
plt.imshow(imInput)
_ = plt.title('Input Image', fontsize=16)


**Approach 2.2** - UnSupervised color deconvolution : Sparse non-negative matrix factorization

In [ ]:
# create initial stain matrix
W_init = W[:, :2]

# Compute stain matrix adaptively
sparsity_factor = 0.5

I_0 = 255
im_sda = htk.preprocessing.color_conversion.rgb_to_sda(imInput, I_0)
W_est = htk.preprocessing.color_deconvolution.separate_stains_xu_snmf(
    im_sda, W_init, sparsity_factor,
)

# perform sparse color deconvolution
imDeconvolved = htk.preprocessing.color_deconvolution.color_deconvolution(
    imInput,
    htk.preprocessing.color_deconvolution.complement_stain_matrix(W_est),
    I_0,
)

print('Estimated stain colors (in rows):', W_est.T, sep='\n')

# Display results
for i in 0, 1:
    plt.figure()
    plt.imshow(imDeconvolved.Stains[:, :, i])
    _ = plt.title(stains[i], fontsize=titlesize)

In [24]:
def unsupervised_matrix(imInput):
    # create initial stain matrix
    W_init = W[:, :2]

    # Compute stain matrix adaptively
    sparsity_factor = 0.5

    I_0 = 255
    im_sda = htk.preprocessing.color_conversion.rgb_to_sda(imInput, I_0)
    W_est = htk.preprocessing.color_deconvolution.separate_stains_xu_snmf(
        im_sda, W_init, sparsity_factor,
    )

    # perform sparse color deconvolution
    imDeconvolved = htk.preprocessing.color_deconvolution.color_deconvolution(
        imInput,
        htk.preprocessing.color_deconvolution.complement_stain_matrix(W_est),
        I_0,
    )

    print('Estimated stain colors (in rows):', W_est.T, sep='\n')
    return imDeconvolved

In [25]:
unsupervised_mtime=[]
images.sort()
print(images)
for i in tqdm(range(0,len(images))):
# for i in range(0,2):
    inputImageFile = 'val/'+ images[i]
    imInput = skimage.io.imread(inputImageFile)[:, :, :3]
    t1 = time.time()
    imDeconvolved =  unsupervised_matrix(imInput)
    unsupervised_mtime.append(time.time()-t1)
    im_c = cv2.hconcat([imDeconvolved.Stains[:, :, 0], imDeconvolved.Stains[:, :, 1]])
    cv2.imwrite("temp.jpg",im_c)
    im_dec = cv2.imread("temp.jpg")
    im_c = cv2.hconcat([imInput, im_dec])
    if i==0:
        final = copy.deepcopy(im_c)
    else:
        final = cv2.vconcat([final, im_c])
# cv2.imwrite("unsupervised_matrix.jpg", final)


['0_0.png', '0_1.png', '0_2.png', '0_3.png', '1_0.png', '1_1.png', '1_2.png', '1_3.png', '2_0.png', '2_1.png', '2_2.png', '2_3.png', '3_0.png', '3_1.png', '3_2.png', '3_3.png', '4_0.png', '4_1.png', '4_2.png', '4_3.png', '5_0.png', '5_1.png', '5_2.png', '5_3.png']


  4%|▍         | 1/24 [00:19<07:37, 19.90s/it]

Estimated stain colors (in rows):
[[5.48681410e-01 7.42603468e-01 3.84042706e-01]
 [4.23350189e-17 8.25525742e-01 5.64364465e-01]]


  8%|▊         | 2/24 [00:41<07:34, 20.65s/it]

Estimated stain colors (in rows):
[[5.40567008e-01 7.46728318e-01 3.87535972e-01]
 [4.41843977e-17 8.24381640e-01 5.66034373e-01]]


 12%|█▎        | 3/24 [01:06<08:04, 23.05s/it]

Estimated stain colors (in rows):
[[5.43321316e-01 7.45638787e-01 3.85778106e-01]
 [4.25522241e-17 8.31006586e-01 5.56262577e-01]]


 17%|█▋        | 4/24 [01:33<08:11, 24.59s/it]

Estimated stain colors (in rows):
[[5.27076947e-01 7.52700339e-01 3.94502333e-01]
 [4.82931248e-17 8.29129380e-01 5.59056770e-01]]


/home/singhv04/.local/lib/python3.8/site-packages/histomicstk/preprocessing/color_conversion/rgb_to_sda.py:48: RuntimeWarning: divide by zero encountered in log
  im_sda = -np.log(im_rgb/(1.*I_0)) * 255/np.log(I_0)
/home/singhv04/.local/lib/python3.8/site-packages/histomicstk/preprocessing/color_conversion/rgb_to_sda.py:48: RuntimeWarning: divide by zero encountered in log
  im_sda = -np.log(im_rgb/(1.*I_0)) * 255/np.log(I_0)
 21%|██        | 5/24 [01:57<07:38, 24.14s/it]

Estimated stain colors (in rows):
[[5.72424751e-01 7.31258848e-01 3.70931801e-01]
 [4.29919634e-17 8.17086180e-01 5.76515546e-01]]


 25%|██▌       | 6/24 [02:15<06:41, 22.28s/it]

Estimated stain colors (in rows):
[[0.59415214 0.72031884 0.35794413]
 [0.04482323 0.82441454 0.56420878]]


 29%|██▉       | 7/24 [02:34<05:59, 21.16s/it]

Estimated stain colors (in rows):
[[5.44369111e-01 7.49225430e-01 3.77257905e-01]
 [4.89481537e-17 8.05940875e-01 5.91996036e-01]]


 33%|███▎      | 8/24 [02:54<05:30, 20.68s/it]

Estimated stain colors (in rows):
[[0.58193098 0.73404649 0.35004584]
 [0.10684832 0.81707208 0.56654802]]


/home/singhv04/.local/lib/python3.8/site-packages/histomicstk/preprocessing/color_conversion/rgb_to_sda.py:48: RuntimeWarning: divide by zero encountered in log
  im_sda = -np.log(im_rgb/(1.*I_0)) * 255/np.log(I_0)
/home/singhv04/.local/lib/python3.8/site-packages/histomicstk/preprocessing/color_conversion/rgb_to_sda.py:48: RuntimeWarning: divide by zero encountered in log
  im_sda = -np.log(im_rgb/(1.*I_0)) * 255/np.log(I_0)
 38%|███▊      | 9/24 [03:12<04:58, 19.91s/it]

Estimated stain colors (in rows):
[[0.49118502 0.77858942 0.39055831]
 [0.07209956 0.814893   0.57510961]]


/home/singhv04/.local/lib/python3.8/site-packages/histomicstk/preprocessing/color_conversion/rgb_to_sda.py:48: RuntimeWarning: divide by zero encountered in log
  im_sda = -np.log(im_rgb/(1.*I_0)) * 255/np.log(I_0)
 42%|████▏     | 10/24 [03:31<04:35, 19.71s/it]

Estimated stain colors (in rows):
[[0.50249849 0.77427707 0.38469505]
 [0.07555966 0.82115747 0.56567761]]


/home/singhv04/.local/lib/python3.8/site-packages/histomicstk/preprocessing/color_conversion/rgb_to_sda.py:48: RuntimeWarning: divide by zero encountered in log
  im_sda = -np.log(im_rgb/(1.*I_0)) * 255/np.log(I_0)
 46%|████▌     | 11/24 [03:54<04:26, 20.51s/it]

Estimated stain colors (in rows):
[[0.50148997 0.77457858 0.38540347]
 [0.08654986 0.81737433 0.56956855]]


/home/singhv04/.local/lib/python3.8/site-packages/histomicstk/preprocessing/color_conversion/rgb_to_sda.py:48: RuntimeWarning: divide by zero encountered in log
  im_sda = -np.log(im_rgb/(1.*I_0)) * 255/np.log(I_0)
 50%|█████     | 12/24 [04:15<04:08, 20.69s/it]

Estimated stain colors (in rows):
[[0.50190476 0.77415214 0.38572021]
 [0.07997966 0.82097289 0.56533775]]


/home/singhv04/.local/lib/python3.8/site-packages/histomicstk/preprocessing/color_conversion/rgb_to_sda.py:48: RuntimeWarning: divide by zero encountered in log
  im_sda = -np.log(im_rgb/(1.*I_0)) * 255/np.log(I_0)
 54%|█████▍    | 13/24 [04:35<03:46, 20.58s/it]

Estimated stain colors (in rows):
[[5.79722596e-01 7.20659888e-01 3.80224982e-01]
 [4.31140160e-17 8.44812910e-01 5.35061816e-01]]


/home/singhv04/.local/lib/python3.8/site-packages/histomicstk/preprocessing/color_conversion/rgb_to_sda.py:48: RuntimeWarning: divide by zero encountered in log
  im_sda = -np.log(im_rgb/(1.*I_0)) * 255/np.log(I_0)
 58%|█████▊    | 14/24 [04:57<03:29, 20.98s/it]

Estimated stain colors (in rows):
[[5.74391633e-01 7.19100110e-01 3.91112878e-01]
 [5.04385354e-17 8.42745443e-01 5.38312287e-01]]


/home/singhv04/.local/lib/python3.8/site-packages/histomicstk/preprocessing/color_conversion/rgb_to_sda.py:48: RuntimeWarning: divide by zero encountered in log
  im_sda = -np.log(im_rgb/(1.*I_0)) * 255/np.log(I_0)
 62%|██████▎   | 15/24 [05:18<03:09, 21.00s/it]

Estimated stain colors (in rows):
[[5.84278897e-01 7.15876328e-01 3.82281642e-01]
 [4.62025319e-17 8.48636289e-01 5.28976794e-01]]


/home/singhv04/.local/lib/python3.8/site-packages/histomicstk/preprocessing/color_conversion/rgb_to_sda.py:48: RuntimeWarning: divide by zero encountered in log
  im_sda = -np.log(im_rgb/(1.*I_0)) * 255/np.log(I_0)
 67%|██████▋   | 16/24 [05:40<02:50, 21.28s/it]

Estimated stain colors (in rows):
[[5.74991867e-01 7.18797861e-01 3.90786372e-01]
 [4.95526707e-17 8.44531511e-01 5.35505861e-01]]


/home/singhv04/.local/lib/python3.8/site-packages/histomicstk/preprocessing/color_conversion/rgb_to_sda.py:48: RuntimeWarning: divide by zero encountered in log
  im_sda = -np.log(im_rgb/(1.*I_0)) * 255/np.log(I_0)
 71%|███████   | 17/24 [05:57<02:20, 20.11s/it]

Estimated stain colors (in rows):
[[5.72065220e-01 7.24758315e-01 3.84014021e-01]
 [4.14526090e-17 8.65989878e-01 5.00061527e-01]]


/home/singhv04/.local/lib/python3.8/site-packages/histomicstk/preprocessing/color_conversion/rgb_to_sda.py:48: RuntimeWarning: divide by zero encountered in log
  im_sda = -np.log(im_rgb/(1.*I_0)) * 255/np.log(I_0)
 75%|███████▌  | 18/24 [06:15<01:55, 19.27s/it]

Estimated stain colors (in rows):
[[5.82186364e-01 7.16783207e-01 3.83771900e-01]
 [4.15504095e-17 8.81793999e-01 4.71634757e-01]]


/home/singhv04/.local/lib/python3.8/site-packages/histomicstk/preprocessing/color_conversion/rgb_to_sda.py:48: RuntimeWarning: divide by zero encountered in log
  im_sda = -np.log(im_rgb/(1.*I_0)) * 255/np.log(I_0)
 79%|███████▉  | 19/24 [06:31<01:31, 18.40s/it]

Estimated stain colors (in rows):
[[5.90613940e-01 7.13244191e-01 3.77435953e-01]
 [4.06936965e-17 8.50816672e-01 5.25462644e-01]]


/home/singhv04/.local/lib/python3.8/site-packages/histomicstk/preprocessing/color_conversion/rgb_to_sda.py:48: RuntimeWarning: divide by zero encountered in log
  im_sda = -np.log(im_rgb/(1.*I_0)) * 255/np.log(I_0)
 83%|████████▎ | 20/24 [06:47<01:10, 17.68s/it]

Estimated stain colors (in rows):
[[5.81783275e-01 7.20120133e-01 3.78094188e-01]
 [4.19898442e-17 8.57712081e-01 5.14130321e-01]]


 88%|████████▊ | 21/24 [07:07<00:55, 18.46s/it]

Estimated stain colors (in rows):
[[5.85536212e-01 7.21323337e-01 3.69918893e-01]
 [5.01987351e-17 8.20482996e-01 5.71670931e-01]]


 92%|█████████▏| 22/24 [07:25<00:36, 18.18s/it]

Estimated stain colors (in rows):
[[0.59311142 0.71818784 0.36390256]
 [0.03991185 0.8089975  0.58645553]]


 96%|█████████▌| 23/24 [07:43<00:18, 18.21s/it]

Estimated stain colors (in rows):
[[0.6000502  0.7156125  0.3575451 ]
 [0.14573878 0.7943007  0.58978522]]


100%|██████████| 24/24 [08:05<00:00, 20.22s/it]

Estimated stain colors (in rows):
[[0.59056089 0.71878426 0.36686105]
 [0.01612915 0.80376148 0.59473299]]


In [26]:
sum(unsupervised_mtime)/len(images)

20.184581408898037

**Approach 2.3** - UnSupervised color deconvolution : The PCA-based method of Macenko et al.

In [ ]:
w_est = htk.preprocessing.color_deconvolution.rgb_separate_stains_macenko_pca(imInput, I_0)

# Perform color deconvolution
deconv_result = htk.preprocessing.color_deconvolution.color_deconvolution(imInput, w_est, I_0)

print('Estimated stain colors (rows):', w_est.T[:2], sep='\n')

# Display results
for i in 0, 1:
    plt.figure()
    # Unlike SNMF, we're not guaranteed the order of the different stains.
    # find_stain_index guesses which one we want
    channel = htk.preprocessing.color_deconvolution.find_stain_index(
        stain_color_map[stains[i]], w_est)
    plt.imshow(deconv_result.Stains[:, :, channel])
    _ = plt.title(stains[i], fontsize=titlesize)

In [27]:
def unsupervised_pca(imInput):
    I_0 = 255
    w_est = htk.preprocessing.color_deconvolution.rgb_separate_stains_macenko_pca(imInput, I_0)
    # Perform color deconvolution
    deconv_result = htk.preprocessing.color_deconvolution.color_deconvolution(imInput, w_est, I_0)
    print('Estimated stain colors (rows):', w_est.T[:2], sep='\n')
    result=[]
    for i in 0, 1:
        channel = htk.preprocessing.color_deconvolution.find_stain_index(
        stain_color_map[stains[i]], w_est)
        result.append(deconv_result.Stains[:, :, channel])
    return result    

In [28]:
unsupervised_pcatime=[]
images.sort()
print(images)
for i in tqdm(range(0,len(images))):
# for i in range(0,2):
    inputImageFile = 'val/'+ images[i]
    imInput = skimage.io.imread(inputImageFile)[:, :, :3]
    t1 = time.time()
    imDeconvolved =  unsupervised_pca(imInput)
    unsupervised_pcatime.append(time.time()-t1)
    im_c = cv2.hconcat([imDeconvolved[0], imDeconvolved[1]])
    cv2.imwrite("temp.jpg",im_c)
    im_dec = cv2.imread("temp.jpg")
    im_c = cv2.hconcat([imInput, im_dec])
    if i==0:
        final = copy.deepcopy(im_c)
    else:
        final = cv2.vconcat([final, im_c])
# cv2.imwrite("unsupervised_pca.jpg", final)

['0_0.png', '0_1.png', '0_2.png', '0_3.png', '1_0.png', '1_1.png', '1_2.png', '1_3.png', '2_0.png', '2_1.png', '2_2.png', '2_3.png', '3_0.png', '3_1.png', '3_2.png', '3_3.png', '4_0.png', '4_1.png', '4_2.png', '4_3.png', '5_0.png', '5_1.png', '5_2.png', '5_3.png']


  4%|▍         | 1/24 [00:00<00:02,  8.33it/s]

Estimated stain colors (rows):
[[0.34600919 0.8127125  0.46880277]
 [0.59710088 0.71688105 0.35993346]]


  8%|▊         | 2/24 [00:00<00:02,  7.49it/s]

Estimated stain colors (rows):
[[0.33220341 0.81552628 0.47387529]
 [0.59379297 0.71907784 0.36102212]]
Estimated stain colors (rows):
[[0.36573217 0.81035407 0.45778407]
 [0.59351913 0.71876957 0.36208472]]


 17%|█▋        | 4/24 [00:00<00:03,  6.36it/s]

Estimated stain colors (rows):
[[0.32023338 0.82125051 0.47222684]
 [0.59549244 0.71654645 0.36324914]]


/home/singhv04/.local/lib/python3.8/site-packages/histomicstk/preprocessing/color_conversion/rgb_to_sda.py:48: RuntimeWarning: divide by zero encountered in log
  im_sda = -np.log(im_rgb/(1.*I_0)) * 255/np.log(I_0)
 21%|██        | 5/24 [00:00<00:02,  6.83it/s]

Estimated stain colors (rows):
[[0.13990484 0.82972669 0.54035197]
 [0.62409175 0.7029664  0.34109783]]


 25%|██▌       | 6/24 [00:00<00:02,  7.21it/s]

Estimated stain colors (rows):
[[0.1290918  0.82957059 0.5432752 ]
 [0.63147987 0.69898336 0.33564182]]


 29%|██▉       | 7/24 [00:01<00:02,  7.05it/s]

Estimated stain colors (rows):
[[0.12679842 0.82576307 0.5495794 ]
 [0.60658787 0.71841667 0.34048294]]


 33%|███▎      | 8/24 [00:01<00:02,  7.00it/s]

Estimated stain colors (rows):
[[0.10516088 0.81835448 0.56501074]
 [0.60724084 0.72107749 0.33362526]]


 38%|███▊      | 9/24 [00:01<00:02,  6.63it/s]

Estimated stain colors (rows):
[[0.11960622 0.82118645 0.55798492]
 [0.52818788 0.7651521  0.36818451]]


 42%|████▏     | 10/24 [00:01<00:02,  6.80it/s]

Estimated stain colors (rows):
[[0.107786   0.82617022 0.55301441]
 [0.54069385 0.75908667 0.36254321]]


 46%|████▌     | 11/24 [00:01<00:01,  6.83it/s]

Estimated stain colors (rows):
[[0.11671611 0.82193658 0.55749225]
 [0.53219294 0.76286985 0.36715156]]


 50%|█████     | 12/24 [00:01<00:01,  6.92it/s]

Estimated stain colors (rows):
[[0.11127571 0.82548605 0.55334482]
 [0.53703465 0.76033238 0.36536073]]


 54%|█████▍    | 13/24 [00:01<00:01,  7.06it/s]

Estimated stain colors (rows):
[[0.21812417 0.83879165 0.4988491 ]
 [0.66770282 0.66460457 0.33537101]]


 58%|█████▊    | 14/24 [00:02<00:01,  7.15it/s]

Estimated stain colors (rows):
[[0.3064886  0.8194989  0.48423784]
 [0.6877917  0.64533848 0.33238655]]
Estimated stain colors (rows):
[[0.2561575  0.8344536  0.48792471]
 [0.70647213 0.63163323 0.31927509]]


 67%|██████▋   | 16/24 [00:02<00:01,  6.51it/s]

Estimated stain colors (rows):
[[0.27884571 0.82513985 0.49131384]
 [0.68594064 0.64704056 0.33290233]]


 71%|███████   | 17/24 [00:02<00:01,  6.80it/s]

Estimated stain colors (rows):
[[0.13801794 0.8629339  0.486103  ]
 [0.63680134 0.68301207 0.35774092]]


 75%|███████▌  | 18/24 [00:02<00:00,  6.71it/s]

Estimated stain colors (rows):
[[0.16343386 0.87065631 0.46394715]
 [0.66143717 0.66077438 0.35479301]]


 79%|███████▉  | 19/24 [00:02<00:00,  6.68it/s]

Estimated stain colors (rows):
[[0.08950287 0.85414039 0.51228257]
 [0.66143196 0.66667639 0.34358458]]


 83%|████████▎ | 20/24 [00:02<00:00,  7.08it/s]

Estimated stain colors (rows):
[[0.13684356 0.85880446 0.49368891]
 [0.66151367 0.66694262 0.34290991]]


 88%|████████▊ | 21/24 [00:03<00:00,  6.94it/s]

Estimated stain colors (rows):
[[0.37804515 0.8018836  0.46267111]
 [0.63668177 0.69103608 0.34220675]]


 92%|█████████▏| 22/24 [00:03<00:00,  7.20it/s]

Estimated stain colors (rows):
[[0.31337963 0.80533062 0.5032254 ]
 [0.62988651 0.69820791 0.34021859]]


 96%|█████████▌| 23/24 [00:03<00:00,  7.31it/s]

Estimated stain colors (rows):
[[0.2319744  0.79746219 0.55699366]
 [0.63169887 0.69960105 0.33393848]]


100%|██████████| 24/24 [00:03<00:00,  6.97it/s]

Estimated stain colors (rows):
[[0.31086722 0.80416353 0.50663852]
 [0.62758485 0.69896171 0.34291367]]


In [29]:
sum(unsupervised_pcatime)/len(images)

0.11124852299690247